/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedSyncRouteImport } from './routes/_authenticated.sync'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedCanaisRouteImport } from './routes/_authenticated.canais'
import { Route as AuthenticatedSyncIndexRouteImport } from './routes/_authenticated.sync.index'
import { Route as AuthenticatedSyncJobsJobIdRouteImport } from './routes/_authenticated.sync.jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncRoute = AuthenticatedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCanaisRoute = AuthenticatedCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncIndexRoute = AuthenticatedSyncIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSyncRoute,
} as any)
const AuthenticatedSyncJobsJobIdRoute =
  AuthenticatedSyncJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedSyncRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sync': typeof AuthenticatedSyncRouteWithChildren
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/sync/': typeof AuthenticatedSyncIndexRoute
  '/sync/jobs/$jobId': typeof AuthenticatedSyncJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/sync': typeof AuthenticatedSyncIndexRoute
  '/sync/jobs/$jobId': typeof AuthenticatedSyncJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/canais': typeof AuthenticatedCanaisRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/sync': typeof AuthenticatedSyncRouteWithChildren
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/sync/': typeof AuthenticatedSyncIndexRoute
  '/_authenticated/sync/jobs/$jobId': typeof AuthenticatedSyncJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/canais'
    | '/configuracoes'
    | '/dashboard'
    | '/sync'
    | '/usuarios'
    | '/sync/'
    | '/sync/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/canais'
    | '/configuracoes'
    | '/dashboard'
    | '/usuarios'
    | '/sync'
    | '/sync/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/canais'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/sync'
    | '/_authenticated/usuarios'
    | '/_authenticated/sync/'
    | '/_authenticated/sync/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync': {
      id: '/_authenticated/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthenticatedSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canais': {
      id: '/_authenticated/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AuthenticatedCanaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync/': {
      id: '/_authenticated/sync/'
      path: '/'
      fullPath: '/sync/'
      preLoaderRoute: typeof AuthenticatedSyncIndexRouteImport
      parentRoute: typeof AuthenticatedSyncRoute
    }
    '/_authenticated/sync/jobs/$jobId': {
      id: '/_authenticated/sync/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/sync/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedSyncJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedSyncRoute
    }
  }
}

interface AuthenticatedSyncRouteChildren {
  AuthenticatedSyncIndexRoute: typeof AuthenticatedSyncIndexRoute
  AuthenticatedSyncJobsJobIdRoute: typeof AuthenticatedSyncJobsJobIdRoute
}

const AuthenticatedSyncRouteChildren: AuthenticatedSyncRouteChildren = {
  AuthenticatedSyncIndexRoute: AuthenticatedSyncIndexRoute,
  AuthenticatedSyncJobsJobIdRoute: AuthenticatedSyncJobsJobIdRoute,
}

const AuthenticatedSyncRouteWithChildren =
  AuthenticatedSyncRoute._addFileChildren(AuthenticatedSyncRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCanaisRoute: typeof AuthenticatedCanaisRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSyncRoute: typeof AuthenticatedSyncRouteWithChildren
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCanaisRoute: AuthenticatedCanaisRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSyncRoute: AuthenticatedSyncRouteWithChildren,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
